FROM ubuntu:latest
RUN apt-get update
RUN apt-get -y install curl unzip nodejs
RUN curl -fsSL https://bun.sh/install | bash
ENV HOME=/root
ENV BUN_INSTALL=${HOME}/.bun
ENV PATH=${BUN_INSTALL}/bin:$PATH
WORKDIR /app
COPY . .
EXPOSE 3000
ENTRYPOINT ["bun", "nodemon"]